# Generated by Django 5.1.4 on 2024-12-11 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customuser_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='password',
        ),
    ]
